### ISSUE TITLE
Stress and Strain mistakes

### ISSUE THREAD

**Issue by FASTNAVi** [scrubbless/PublishedScenarios#10]
Hello! We just finished your scenario and spotted some mistakes..

1) When you place a darkness on square and storefront, you have bad names of tiles.. later they are correct when you discard darkness.

2) You have a lot of typos. I really feel pain every time I see a "face down"... it is one word. I don't want to say that my scenario will be without typos but you can improve your scenario. No offense =)

3) This is just an idea from my own creating of scenarios. There is no bladed weapon. This is important for one of the insane conditions for winning. Maybe you can insert one somewhere... ;-) (well, I just realized we played it in 2 players.. bladed weapon is needed for insane card for 3 players.. if you add bladed weapon only if it is there 3 or more players, please ignore this)

At the end it is still the best scenario we already played in Valkyrie so far. Thank you very much for your job! We will play it once more for sure!

**Comment by scrubbless** [comment]
Thanks for the feed back (see what I did there!! Haha).

I welcome all feedback, I am quite thick skinned so won't take offence easily, especially if it's intended to be constructive.

Thanks for identify the typos, I need to fire up the official app and see what words they use for face down (facedown). My interpretation is face (the face of the card) down (down on the table) as two words, I don't think I've seen poker or any other cards referred to as facedown. Regardless I'll emulate whatever the official app says. There is a good chance I messed it up!

Good call on the bladed weapon. I actually randomise as much as I can, but you are right about the insane conditions. I'll go through the cards and make sure I have at least something to fulfill all insane win condition. 

I'll also visit that darkness and get it right! 

Appreciate the feed back! Thanks again!

**Comment by scrubbless** [comment]
Let me know how you found the second play, I've added a little variety, but there is a 1 in 4 chance you'll get the same one.

Also if you have a Board Game Geek account, I would really appreciate it if you would rate (and/review) my scenario (or any you have played), in this thread:
https://boardgamegeek.com/thread/1916430/fan-made-scenarios-reviews-valkyrie

**Comment by scrubbless** [comment]
I stand corrected it is "facedown", just hit Google and checked the official app.

**Comment by FASTNAVi** [comment]
Of course, I am on same ship like you ;-) I am maybe a little bit perfectionist so my completed scenario is still only in my PC and I am testing it over and over again but I will be also very grateful for any feedback after release..

For the insane cards.. you just need at least one bladed weapon, light source and evidence in every scenario (mean to included 3+ insane cards) =)

**Comment by scrubbless** [comment]
Have you considered using GitHub to track changes and create backups/revisions?

Also let me know when you have published and I'll play and give feedback.

I am about 80% complete on my next scenario. Some cool bits in there so hopefully it will be better than my first.

**Comment by FASTNAVi** [comment]
Yeah, I consider but so far I don't need it. My scenario is done and I am changing just small things.. From work I am use to make a backup often.

About my new scenario. I take a really big goal so I think, reallistic, I will be finish with it in 3 or 4 months.. But it will be long scenario with a really big variety. 

Btw the truth is, I am working on campaign of three scenarios. Between scenarios, you can of course discard all damage and horror, you must also discard all items. If you decide to play directly part 2 or 3, you can, you will just missing some important information, but it will be possible finish that scenario. So it will be like story campaign.. I wonder if it was a good idea to start with it.. will see :)

Yeah, of course I will be very happy if you play my scenario. I also like feedback with information like number of players (investigators), time of game, ending.. I hope scenario will be here in 2 weeks.

**Comment by scrubbless** [comment]
That sounds awesome! How are you linking the acenarios? 

3 independant scenarios with discriptions that say 1-3. Or are you using the descent model and having a campaign mode? I wanted to do something like that with a map and over arching story/equipment. But it's a bit ambitious I have more to learn!

**Comment by FASTNAVi** [comment]
Well, I was thinking about this so much.. But I am afraid, it is almost impossible to go from one scenario to another with all items etc. You know, somebody is playing just one scenario per week/month and will be very difficult to remember all that stuff.. So my model will be like 3 standalone scenarios connected with the main story. First scenario will be in the dawn, second in the middle of the night and last will be around sunset next day, so everything in 12 hours.. Every scenario will end with something, what explain the loss of items.

I do not order to players some rules, but it will be good if whole 3 scenarios will be played with the same investigators. You cannot keep all horrors and damage, because that game would be so difficult. Maybe keep just faceup? Or keep faceup and changed them to facedown before start? I don't know.. this need a testing.. But like I said.. basic idea is long story separated into 3 scenarios.

**Comment by scrubbless** [comment]
Sounds interesting.

I plan to learn how to create Quests in Valkyrie's Descent module at some point. It seems that you can link Quests (Scenarios) to each other. So the idea being you have a single scenario to trigger the campaign. This in Descent is a map, with locations that pop up (a UI element, with other UI elements dropped on top, which have clickable actions to trigger random events and steer the story).
When you click a side mission in the Campaign mode, (after the random events) it takes you to the side mission, which in Valkyrie is just a call in the Quest.ini telling Valkyrie to launch a different quest (scenario). I assume you can pass variables back and forth, e.g. "Win Mission 1 = 0" "Win Missions 2 = 1". So you can capture the results and things that happened in the side missions in the "Campaign" and players just save the state of that campaign mission. 

It would be completely possible to do the same in Valkyrie. So you track the equipment in the Campaign (and you have a checksum after each scenario - "Do you have these items" click to deselect items you don't have"). I suspect there would need to be rules on what you can carry, otherwise each investigator would be loaded with millions of items.

Anyway, it all sounds rather complicated and not something I plan to do any time soon!

**Comment by scrubbless** [comment]
I'll get these in version 4 along with another set or errors submitted by Mam's.

Thanks again! Good luck with your scenario (s), I look forward to playing it/them.

**Comment by FASTNAVi** [comment]
Uploaded ;-)

**Comment by scrubbless** [comment]
Awesome, I lent my copy of MoM to a friend so can't play it yet. But I will let you know on the bgg feedback thread (and issues to you GitHub) when I do!

On the Ashcan Pete issue, we discussed how to quit the scenario if players select certain heroes.

You could use a Test before your intro to check if #heroashcanpete = 1 then end the scenario if it triggers. That way players are unable to play the scenario if they pick the banned character!

Also announce it in the Valkyrie scenario feedback thread to get some publicity!
https://boardgamegeek.com/thread/1916430/fan-made-scenarios-reviews-valkyrie

**Comment by scrubbless** [comment]
Ok thanks for your help FASTNAVi.

> When you place a darkness on square and storefront, you have bad names of tiles.. later they are correct when you discard darkness.

Fixed, this was from when the event used to trigger on the "North Street" in version 1.

> You have a lot of typos. I really feel pain every time I see a "face down"... it is one word. I don't want to say that my scenario will be without typos but you can improve your scenario. No offense =)

I think I got every reference to "facedown" and "faceup" in there. Let me know if you find any more in v2.4.

> This is just an idea from my own creating of scenarios. There is no bladed weapon. This is important for one of the insane conditions for winning. Maybe you can insert one somewhere... ;-) (well, I just realized we played it in 2 players.. bladed weapon is needed for insane card for 3 players.. if you add bladed weapon only if it is there 3 or more players, please ignore this)

I have added a bladed weapon (no hero limit), I had an event that was overly punishing, so i've compensated it with a bladed weapon! :D

I'll close this issue off. Thanks again for your feedback and rich discussion!
