### ISSUE TITLE
Spoiler - About Boat Ending

### ISSUE THREAD

**Issue by mamantins** [scrubbless/PublishedScenarios#11]
Hello,

I just run the scenario and I try to leave with the Boat.
This ending do not "finish" the game.
Maybe it's wanted, maybe not, but I was surprise to the possibility to "goes back".

i hope this help.
I have to run it again. :)
I failed finally.

Mam's

**Comment by scrubbless** [comment]
Hi mam's,

The boat interact is intentional. It is meant to be a way to flee if things go very wrong. It won't spawn unless certain circumstances are met (have fuel + deadly mythos triggers)
The scenario is meant to be easy, but it can get very hard if corpses are not dealt with, so having an "escape" helps mitigate that risk.

The flavour text is meant to make you feel that you could have done better. But ultimately the goal of the scenario is to avoid whatever is happening in Ambersby.

What happened when you tried to use the token,did it work ok? Did it not show the end text?
What version of the client are you using?

Or are you just surprised with that particular ending? :)

There are three other ways to win the game without failing.

**Comment by scrubbless** [comment]
Other than that, did you enjoy the scenario? Is there anything you didn't like or think could be improved?

**Comment by mamantins** [comment]
scrubbles, 
I liked your scenario. 
I play alone and I like the global feeling of it. 
Seriously you did a great job. (Balance between fight and investigation is great) 

I did not reach the good ending, Yet. 
I will set fire to the « room » next time, but the trigger behind this scare me. ;)

On the other hand I was very please to see a « small » map with so many interaction. 
I like it.  At least It’s « portable ». 
My  scenario have currently a far bigger map… I should reduce it. Drastically. 

Finally regarding the issue. 
Following my own feeling one of my investigator was beeiing crushed by the  « horror » so the other one run away. :)
When I trigger the interaction a new screen appears with the text… 
But my  options to get out was to : 
- Select the main menu to get out of the game. 
- Select go back to continue playing. 
I would expect a continue button to « close «  the adventure. 

Another « issue » spotted. 
A zombie was already on the field and the guy in the south house turn into zombie also. 
No sign was set to identifying the last one. (Still it's not difficult to manage for the player) 

I will play it again. With my girlfriend this time. 

Mam's 
Note: More I play MoM less I like the system of the Horror Test each turn.
You reduce the dangerousity of the dice roll. I likes that. :)
I guess I will remove completly those dice roll from my own scenario to focus more on Myht event.

**Comment by mamantins** [comment]
This last point...
I took some horror card because of bad luck to the dice roll...
So one of my character became crazy after 3 turn fighting and missing to hit the zombie. (and missing some easy throw in the horror test.)
Rolling dice for rolling the dice is not really interesting. (I really appreciate one of your event where everyone took 2 horror because of the global situation. :) )

**Comment by scrubbless** [comment]
> Select the main menu to get out of the game.
> Select go back to continue playing.
> I would expect a continue button to « close « the adventure.

Just to respond to this, apologies I will get to the rest of this later (got a bunch of meetings today!)

I am not aware of a way to exit a scenario from an event. I will have to look into this. If it is possible I will do so. However the dialog test should have "The End" on it, which I like to think wraps up the narrative of the scenario :D.

If you want a little difference in your next play, try taking 6 investigators :D. I suspect it will be easier, but I have added some optional content for 6 players.

**Comment by scrubbless** [comment]
Note: More I play MoM less I like the system of the Horror Test each turn.
You reduce the dangerousity of the dice roll. I likes that. :)
I guess I will remove completly those dice roll from my own scenario to focus more on Myht event.

I like using negates, rather than pass/fail. Also giving -1 but less to negate feels better for gradual insanity to me. It bugs me that you best chance of competing a scenario is to pick will 4+ investigators. Wounded conditions are nowhere near as bad as insane conditions

**Comment by mamantins** [comment]
Just to respond to this, apologies I will get to the rest of this later (got a bunch of meetings today!)

I am not aware of a way to exit a scenario from an event. I will have to look into this. If it is possible I will do so. However the dialog test should have "The End" on it, which I like to think wraps up the narrative of the scenario :D.

If you want a little difference in your next play, try taking 6 investigators :D. I suspect it will be easier, but I have added some optional content for 6 players.

==> You can use the variable #BoardComponents in Remove items. (^_^)

**Comment by scrubbless** [comment]
==> You can use the variable #BoardComponents in Remove items. (^_^)



I am sure I put that in, that and #monsters

**Comment by scrubbless** [comment]
> ==> You can use the variable #BoardComponents in Remove items. (^_^)

I am sure I did that, as well as the remove  monsters one. But it just leave you with a blank screen and you still have to main menu > exit.

**Comment by scrubbless** [comment]
Ok to reply to the rest:

> I did not reach the good ending, Yet.
I will set fire to the « room » next time, but the trigger behind this scare me. ;)

Doo it! Some people just wanna see the world burn. Though there is another way to win without fire or running away!

> On the other hand I was very please to see a « small » map with so many interaction.
I like it. At least It’s « portable ».
My scenario have currently a far bigger map… I should reduce it. Drastically

The first map was alot bigger, there was a street going north and an alley going east. Felt more like a town, but ended up having players spend far too long just moving (4 spaces - their whole action. I try to avoid that, it's super boring). You could mitigate that a little by adding shortcuts. But I found it feels more dynamic to have a smaller map and then use random or late game events that reuse tiles. This makes the map feel more alive.

> Another « issue » spotted.
A zombie was already on the field and the guy in the south house turn into zombie also.
No sign was set to identifying the last one. (Still it's not difficult to manage for the player)

I am not sure what you meant here? I have seen some odd lag issue in Valkyrie where it registers multiple clicks and you can accidently skip a dialog. Maybe that was the issue.

Thanks for the feedback. I have loads on my list for version 2.4! 
I will get round to working on them when I finish a particular event chain in my current scenario. I am doing a really complicated and quite randomised situation, which is taking a huge amount of focus, so don't want to break away from it until I nail it down.

Its like a whole new puzzle in its own right, using UI elements.

**Comment by scrubbless** [comment]
> I just run the scenario and I try to leave with the Boat.
> This ending do not "finish" the game.

I was not even aware that adding an event called "EventEnd" would exit the scenario! I have a load of them in the next scenario I am writing to donate events that happen at "RoundEnd".

I better change that for backward compatibility too!

Regardless I have added a "The End" button to all endings, that will exit the scenario. Thanks for pointing this out!

> A zombie was already on the field and the guy in the south house turn into zombie also.
> No sign was set to identifying the last one. (Still it's not difficult to manage for the player)

Ahh I will look into this, that second zombie is a "Custom Monster" so it may not have understood that it used the same model. I'll check it out!

**Comment by scrubbless** [comment]
They are all set with the base "MonsterZombie" so I am not sure whats going on. I will test some more and raise a bug on the Valkyrie github if I can't solve it.

Thanks for the feedback. I'm closing this issue off !

**Comment by mamantins** [comment]
Thanks a lot for the feedback.

On my side I played your scénario twice after this first try.
I succeed to reach the good ending and another thrid one.

Still did not try with 6 investigators :)
Franckly, I like the feeling of this scenario.
GG

**Comment by scrubbless** [comment]
How was the replayability? I tried to add some varying situations but it was hard to retro-fit (change after the first build).

My next scenario has alot of variable events and clue chains. So may be a little better than this one.
