### ISSUE TITLE
No more Horror Tests after Shoggoth Horror Test

### ISSUE THREAD

**Issue by harrislalo** [scrubbless/PublishedScenarios#12]
Hello,

When Shoggoth enemy is in play, if you do a Horror Test against the Shoggoth, no more Horror Tests against other enemies are allowed, Mythos phase just end when clicking in Continue button. Therefore, investigators who need to resolve a Horror Test against other enemies in play should do it first.

Regards,

**Comment by scrubbless** [comment]
Oh, that's odd. Let me check that out. The shoggoth was added quite late as an alternative to the dunwich horror.

**Comment by scrubbless** [comment]
Thats really weird, its as if the horror check ends the horror phase. I think this is a Valkyrie bug as there is nothing in the Horror tests to tell the mythos round to end.

I've raised a bug report for it here:
https://github.com/NPBruce/valkyrie/issues/841

Thanks for bring this to my attention, it will help refine the Valkyrie application as well as my own scenario!

**Comment by harrislalo** [comment]
I realized that Mythos phase finished in the case of Horror tests against Shoggoth and Deep Ones but not against Zombies. This information could help for the bug in Valkyrie.

**Comment by scrubbless** [comment]
Thanks @harrislalo, I'll take a better look at each monster. It looks like something to do with the way custom monster horror checks work. Specifically when you create your own horror activation for them.

I produced the same error with a riot custom monster, but I'll definitely do the same with some zombies and deep ones.

**Comment by scrubbless** [comment]
I found that if you have an item with an inspection action. Doing so during the horror phase will also end the horror phase.

**Comment by scrubbless** [comment]
Hi @harrislalo.

BenRQ fixed this in his Brunhilde beta. This is a branch of Valkyrie which we are hoping Bruce will merge into Valkyrie when he gets back to working on Valkyrie.

 https://github.com/BenRQ/valkyrie/releases/tag/release%2F2.0%2Fv2.0.2b

It has a built in reviews system and fixes the save and auto save issues currently in 2.01.
