### ISSUE TITLE
Confusing text and image in Stress and Strain for the Blue vial

### ISSUE THREAD

**Issue by harrislalo** [scrubbless/PublishedScenarios#13]
Juast take a look to highlighted text and image:

![image](https://user-images.githubusercontent.com/39581698/40887807-660c1556-674e-11e8-976c-ba1fd9fe355c.png)

Thanks

**Comment by scrubbless** [comment]
Oh, that's not good. I need to fix that!

Originally there was only one clue chain and evidence. But after the initial release I decided to add 4 variations of the clue chain. Looks like I messup a UI elements here.

Hope it didn't ruin your game. :)

**Comment by scrubbless** [comment]
Not sure if you use BGG, but if you do and have time, would you mind dropping a rating on the Valkyrie thread and a review if you fancy it. Will help spread awareness of Valkyrie.

https://boardgamegeek.com/thread/1916430/fan-made-scenarios-reviews-valkyrie

Thanks for your bug reports and for playing the scenario, I hope you enjoyed it, despite these bugs.

**Comment by scrubbless** [comment]
Ok I have fixed this one, the UI element was correct and I must have forgotten to update the text.

Thanks again!

**Comment by scrubbless** [comment]
Reopened, not sure if you read the other comments.
