### ISSUE TITLE
Question about editor

### ISSUE THREAD

**Issue by FASTNAVi** [scrubbless/PublishedScenarios#15]
Hi @scrubbless ,

I have a question. In your last scenario, you manage to make a scenario for basic game but allow to play with components from the expansions. How did you do that?

Because only solution, what I can do, is just make a lot of conditions and that is not very pretty. I prefer some elegant and simply solution.

Thank you very much in advance for your answer!

**Comment by scrubbless** [comment]
There are built in variables. When you select an expansion is sets the variable: #expansion to 1.


E.g.

Streets of Arkham selected:

#SoA = 1

Create your event for Streets of Arkham and in the first event in the chain set the TEST

#SoA == 1

If streets of Arkham is in the content library it runs the event. If it's not, don't run the event.

So I tend to set an event where the path can split. In this event I'll make a 'path' for base only and then a second path for a differen expansion.

I actually did this in Stress and Strain too. There is a crate of pills in 4+ players that uses SoA improvements.

**Comment by FASTNAVi** [comment]
OK, so that solution I already know.

Thank you very much for your answer.
