### ISSUE TITLE
Polish translation to Stress and Strain

### ISSUE THREAD

**Issue by zcaalock** [scrubbless/PublishedScenarios#16]

**Comment by zcaalock** [comment]
Here is the file.
[Localization.Polish.txt](https://github.com/scrubbless/PublishedScenarios/files/2585251/Localization.Polish.txt)

btw is the StrainOnReality continuation to Stress and Strain?

**Comment by scrubbless** [comment]
Thank you! I'll update it tomorrow!

A Strain on Reality is a continuation of the story.

**Comment by scrubbless** [comment]
Hi @zcaalock 

I have updated some events to fix some bugs, can you translate the following passage and i'll update the event text.

AbanHouse_ApproachDuke_Passed_NoAshcan


The dogs bows its head and lets you stroke him. After a few moments you manage to get his tail wagging. Satisfied, you smile and stand up to leave. The dog obviously doesn't want to leave his owner, however he pads over to you and tugs at your clothing, before raising his head. Around his neck is a collar with a strange looking pendant attached. The owner must have cared deeply for his pet to adorn it with what appears to be a family heirloom. The animal seems to want you to take the item, so you slide it off as you pets him for a few more moments.

Gain the {c:QItemNoDuke} unique item.

Remove the Person token

**Comment by zcaalock** [comment]
Pies pochyla głowę i pozwala ci się pogłaskać. Po kilku chwilach widzisz jak macha ogonem. Uśmiechasz się z satysfakcją i wstajesz aby odejść. Pies nie ma zamiaru zostawiać swojego właściciela, jednak podchodzi do ciebie i szarpie za ubranie, następnie patrzy się na ciebie wymownie pokazując szyję. Jego szyję oplata obroża z dziwnie wyglądającym wisiorkiem. Właściciel musiał bardzo kochać swojego psa, bo przyczepił do jego obroży coś co wygląda na rodzinną pamiątkę. Pies najwyraźniej chce abyś to wziął ze sobą. Odpinasz wisiorek i jeszcze przez chwilę drapiesz go za uchem.

Otrzymujesz przedmiot unikatowy {c:QItemNoDuke}

Usuń żeton Osoby

**Comment by scrubbless** [comment]
Awesome, all done. You should see an available update in the download list. 

Thanks very much for doing this translation!

**Comment by zcaalock** [comment]
i found some mistakes in new version. Take a look here
https://docs.google.com/spreadsheets/d/1W1bI8754fTw_uxXdTYZLyBMs_60ZJ0jttK3FpNHPK_I/edit?usp=sharing

It is marked with red. Go to sheet: "combine" in column C. 
As you can see, some of the lines starts with /n
I can remove them and compile english and polish version and send you.
