### ISSUE TITLE
French translation - Stress and Strain

### ISSUE THREAD

**Issue by BenRQ** [scrubbless/PublishedScenarios#18]
Here is the final version of the French translation after some test.

A few points to update in the scenario itself, to adapt to French translation: 
1) Can you please deactivate the audio voiceover at the beginning when in French?
It's very difficult to read in French when someone is speaking in english at the same time.

2) Can you please increase the size of the start button?
You should read "Commencer" down here in the button, and all equivalent translations for "start" are quite large : 
![Screenshot_2019-03-17-22-04-28-063_com bruce valkyrie](https://user-images.githubusercontent.com/40794717/54498015-d6db4500-4901-11e9-900d-91f48599be53.png)

[Localization.French.txt](https://github.com/scrubbless/PublishedScenarios/files/2977348/Localization.French.txt)

Regarding pictures with text, do you want me to provide text as I see it in the picture ?
Or it will be too much work for you to update pictures too ?

**Comment by scrubbless** [comment]
Is there functionality to detect when a scenario is played in french? 

If not i'll create a blank audio file for the dialogue and put it in the "French" folder in the scenario.
I'll increase the size of the box to make the start button fit.

**Comment by scrubbless** [comment]
Ok all done, I added a different music audio file (from A Strain on Reality's custom music list) with the intros name into two folders "French" and "Polish", so music will play instead of the spoken english intro.

**Comment by BenRQ** [comment]
How long is your audio file ?
If it is one second, then the standard background music should start after your file.

**Comment by scrubbless** [comment]
It was one second, It'll be fine with the other music. I am actually considering having a look for an appropriate royalty free music for that intro anyway.

Its live, so please feel free to test and communicate on your french facebook group :)

**Comment by scrubbless** [comment]
If you are interested in translating the UI elements, I would happily create updated language specific ones for them.

If you would prefer to update them yourself they should all be in this repo, I use GIMP so the .xcf files are all in there (under XCF Templates):

https://github.com/scrubbless/Scenario-Media

**Comment by BenRQ** [comment]
OK nice, I will give you the translated text to integrate in the picture, it would probably easier.

**Comment by BenRQ** [comment]
By the way, you can probably remove the investigator.png and mythos.png files :)

**Comment by BenRQ** [comment]
![Blackboard.png](https://user-images.githubusercontent.com/40794717/54679370-67cf3d80-4b07-11e9-8abb-2e5e61a7fa25.png)

For all blackboard pictures (only the numbers should be changed): 
```
Utiliser le stabilisateur #9252 en dernière
étape pour toutes les combinaisons.
```

![drchannote](https://user-images.githubusercontent.com/40794717/54679569-e2985880-4b07-11e9-928b-2419387772dd.png)
```
Docteur Chan vous explique qu'un liquide vert est utilisé comme composant pour un genre de sérum.
C'est un stabilisateur, mais il est particulièrement instable si il n'est pas utilisé correctement.
```
![Inventory](https://user-images.githubusercontent.com/40794717/54679692-3c008780-4b08-11e9-9b77-4d135b47bd3c.png)

```
La Compagnie du Centaure

Commande #00043

15 fioles:
#2734 - Liquide orange, élément un de X52
agent de neutralisation.

Divers outils
```

InventoryVar3.png:
```
La Compagnie du Centaure

Commande #00043

15 fioles:
#7334 - Liquide vert, élément un de X52
agent de neutralisation.

Divers outils
```

InventoryVar3p2.png:
```
La Compagnie du Centaure

Commande #00043

15 fioles:
#6544 - Liquide bleu, élément deux de X52
agent de neutralisation.

Divers outils
```

InventoryVar4p1.png:
```
La Compagnie du Centaure

Commande #00043

15 fioles:
#9252- Liquide rouge, élément un de X52
agent de neutralisation.

Divers outils
```

**Comment by BenRQ** [comment]
![Journal](https://user-images.githubusercontent.com/40794717/54680387-fcd33600-4b09-11e9-8628-d1af3473effd.png)

```
~Quai 1~
Disponible

~Quai 2~
Crête de Vague, place permanente du Shérif Robins, pas actuellement amarré, à l'atelier pour réparation

~Quai 3~
Vaisseau de recherche 1, Dr Joyce Little, partie précipitamment. À laisser une facture "La Compagnie du Centaure" à régler.
```

![JournalInventory](https://user-images.githubusercontent.com/40794717/54680772-027d4b80-4b0b-11e9-8423-047f0fdac63f.PNG)

```
~Bidon de Carburant~
Stock vide, en attente de livraison

Vente récentes
Shérif Robins, un bidon

Dr Little, Quai 3, un plein

Achat matériel:
Arme à feu, sous clef dans l'armoire à armes, pas à vendre

Non répertoriés:
Quai 3 - divers
```

![paperdeadman](https://user-images.githubusercontent.com/40794717/54681143-eded8300-4b0b-11e9-9e0c-31e59b6d7e58.png)

```
La Compagnie du Centaure
6A
```

![sign](https://user-images.githubusercontent.com/40794717/54681186-08276100-4b0c-11e9-88a3-c65c509739fb.png)

```
Rue Nord
Bureau du Shérif - Librairie

Rue Est
Quartier résidentiel
```

![slip](https://user-images.githubusercontent.com/40794717/54681270-386eff80-4b0c-11e9-8f71-fa6528f664c6.png)

```
Seconde partie Bleue !
Arrête d'oublier !!
```

![slipVAR2](https://user-images.githubusercontent.com/40794717/54681278-3c028680-4b0c-11e9-8f49-5a196d8479c1.png)
```
Seconde partie Verte!
Arrête d'oublier !!
```

**Comment by BenRQ** [comment]
Ok they should all be here :)

**Comment by scrubbless** [comment]
Amazing thanks @BenRQ 

I'll take a look, some of these I merged the text blur and smudge, but i'll work it out and get you those variations.


EDIT: Turns out I only started filing the the XCF files with A strain on reality. May have to edit the PNG's themselves :D

**Comment by scrubbless** [comment]
Don't suppose you speak polish too do you? Haha

**Comment by scrubbless** [comment]
@zcaalock would you be able to translate the text on the above images?

I'll update the images for the polish translation if you can.

**Comment by BenRQ** [comment]
I know only one word in Polish : "Culva !"
Don't try to translate it :)

**Comment by scrubbless** [comment]
All done, I am just uploading the update now.

![image](https://user-images.githubusercontent.com/32058089/54690175-bdf8ac80-4b18-11e9-9217-7d011802337d.png)

**Comment by scrubbless** [comment]
Let me know if it looks ok :) I did run it through and mechanically its sound (I don't understand much french but I know every bloody event in that scenario of by heart).

**Comment by BenRQ** [comment]
All the pictures are good :)

But damn... in the ONE picture you take as an example, I see a problem in the text.
The name of the company is not translated, it should be "La Compagnie du Centaure" and not "The Centaur Company".

Here is the fix:
[Localization.French.txt](https://github.com/scrubbless/PublishedScenarios/files/2988692/Localization.French.txt)

**Comment by scrubbless** [comment]
Haha I'll get that fixed

**Comment by zcaalock** [comment]
i`ll do the translation in the evening today

**Comment by scrubbless** [comment]
No rush @zcaalock just when you have time.

**Comment by zcaalock** [comment]
1. use stabiliser..
Użyj stabilizatora #9252 jako ostatni element kombinacji.

2. dr Chan..
Dr Chan wyjaśniła, że zielonej cieczy używa się jako komponent do serum. To jest własnie Stabilizator, Źle zmieszany zmienia się szybko w gaz.

3. The centaur company
Firma Centaur
Zamówienie #00043

4. 
15 fiolek:
#2734 - pomarańczowy płyn, część pierwsza z X52
Środek neutralizujący
Różne narzędzia

5.
~ Dok 1 ~
Dostępny
~ Dok 2 ~
Szczytowa Fala, stałe miejsce łodzi Szeryfa Robins, obecnie nieużywany, w trakcie naprawy.
~ Dok 3 ~
Statek badawczy 1, dr Joyce Little, oddaliła się w pośpiechu. Należy uregulować fakturę: „Firma Centaur”.

6. 
~ Paliwo w beczkach ~
Pusty magazyn, czekam na dostawę

Ostatnia sprzedaż:
Szeryf Robins, 1 beczka

Dr Little, Dok 3, pełny

Zakupy do biura:
Pistolet, zamknięty w szafie na broń, nie na sprzedaż

Nie wymienione:
Dok 3 - różne

7. The Centaur
Firma Centaur
6A

8. North/south street
Północna ulica
Biuro Szeryfa - Księgarnia
Południowa ulica
Rezydencje

9. Second part blue
Cześć druga - niebieski
Nie zapomnij!

10. Second part green
Cześć druga - zielony
Nie zapomnij!

**Comment by scrubbless** [comment]
Amazing thanks @zcaalock

**Comment by scrubbless** [comment]
Thank you @zcaalock, all UI elements have been updated with your translations.
@BenRQ  for some reason your file did not work, so I fixed the Centaur Company bit above manually.

v3.5.3 is out, now have translated UI elements for Polish and French!
![image](https://user-images.githubusercontent.com/32058089/54791906-c5f93f00-4c33-11e9-90f0-a6ef426915d4.png)
