### ISSUE TITLE
Stress and Strain Version 2

### ISSUE THREAD

**Issue by scrubbless** [scrubbless/PublishedScenarios#2]
I have rewritten Stress and Strain in Valkyrie 1.6.1.
The story is the same, but there are a lot of ease of life and cosmetic changes, which help to speed the game pace up and reduce the amount players need to move.

Changes:

- I have refined the expansion requirements to just Recurring Nightmares (or 1st ed).
- Removed redundant tiles, ~half of the board and retuned how players can progress - giving them more route options and reducing the number of turns required to complete the investigation.
- Added optional content based on expansions. Such as different monsters and items.
- Added support for 6 players
- Non plot specific events have been tagged to spawn based on player numbers, to avoid an influx of "filler" tokens and events from distracting smaller parties (and giving larger parties more to do)
- Had to remove French translation due many changes in V2.

**Comment by scrubbless** [comment]
I am adding more variation, to help with multiple plays and tuning it nearer to 3 star difficulty.

**Comment by scrubbless** [comment]
Added additional content for 6 players and added 3 'variations' on evidence order, to help keep repeat plays varied.

**Comment by Indoy** [comment]
Hi !
when downloading v2, scenario isn't in french anymore :(
As i posted earlier, if you need some help to translate some news lines i'm on =)
Regards

**Comment by Indoy** [comment]
oops i'm still in v1.6.1, is there a link with this fact?

**Comment by scrubbless** [comment]
Hi Indoy. 

1.6.1 is the correct version, I managed to make the content I created in 1.7.0b backwards compatible to 1.6.1.

I removed the French Localisation file, because I made significant changes to the events and dialog.
I would love it if you would like the update your french version so that I can re-add it?

The French localisation file is still in the Scenario's files, I just un-linked it from the scenario for now.

**Comment by Indoy** [comment]
Yes you can send me the changes! Or is there any ways to spot what's needed to be translated ?

**Comment by scrubbless** [comment]
Hi Indoy, no worries.

There are a lot of changes. I have copied the Version 1 (the one you translated) Localisation.English file. I then uploaded this as a file on GitHub. I then replaced the same file with the latest localisation file.

The version history shows the changes between the two versions.

It can be found here:
https://github.com/scrubbless/ScenariosInProgress/commit/aa48e52320dcc77c9690124e6b570f6d9647037e#diff-8b532f3af5b2aa5e109c918bb548d0de

**Comment by Indoy** [comment]
So, if i understand well, i'm supposed to translate (or only modify one or two words) what's appearing in green with a "+" in front of ?

**Comment by scrubbless** [comment]
This it, the green changes are the new text I have added.

**Comment by scrubbless** [comment]
Hi @indoy, do you need any more assistance from me with the translation?

**Comment by Indoy** [comment]
Hi!
Sorry no much time, there is lot to do... but i keep it mind !
Don't worry i'll do it!
Regards

**Comment by scrubbless** [comment]
Oh no rush Indoy, I've seen how many changes Nicola has you working on for "In the Dark"!

Just wanted to make sure the change tracking linked above was what you needed.

**Comment by scrubbless** [comment]
Linking to #1 and closing

**Comment by Indoy** [comment]
@scrubbless 
Hi!

Work in progress for the v3.0. However line 494 you indicated a (missing link) for the fuel canister. Should I remove completely the former link {c:QItemQItemFuelCan} ?

Thx

**Comment by scrubbless** [comment]
Hi Indoy, I'll take a look and get back to you. From memory I think I specifically called out the fuel canister and missing link to correlate the two. Players probably wouldn't have remembered that "Missing Link = Fuel Canister".

**Comment by Indoy** [comment]
@scrubbless 

Hi!
Lost my HDD... and the half of my former translation... However i'm waiting for extracting (hope so) some of my HDD contents.... But i suddenly realise that i might directly make translation on the file you've linked to me (scrubbless/ScenariosInProgress@aa48e52#diff-8b532f3af5b2aa5e109c918bb548d0de). If i click on a "+" under each lines i could write the tranlation? Sorry i'm not familiar with Github's use... If yes i'll do the end of all the additions you've made and i'll add  (what i've already done) later when i get my HDD back.

**Comment by scrubbless** [comment]
I believe you will need to branch from my master (may require a pull request) - and you will need GitHub to do so.

Once you have my code you can do your edits in your branch and when complete request to merge it into the master.

**Comment by Indoy** [comment]
@scrubbless 
Hello,
I had get my DD back... i'll go on translating =)

One question : i'm doing some research about the righteous state. What kind of state is it? From a new expansion? Or is it "Concentrated"? --Thx

picked up from : "EventBeachItemEvent7_SoA_Tile4.text,You swallow some of the pills, pausing for a moment you wait to see if they have any effect.\n\nYou feel a surge of self confidence. You feel as if you can overcome any obstacle, become Righteous"

**Comment by scrubbless** [comment]
Righteous is a state from SoA, it allows you to convert a clue into a success automatically once per round. But you discard the condition when you take horror.

The word righteous is similar to 'empowered'  having noble or honourable goals.

I use variables to check if #SoA is selected as an expansion before I allow the event to run.

**Comment by scrubbless** [comment]
Hey indoy I'll close this issue for now.
