### ISSUE TITLE
Suggested improvements for Stress and Strain

### ISSUE THREAD

**Issue by NicolaZee** [scrubbless/PublishedScenarios#20]
Hello James

I have two small improvements for Stress and Stain.

1. Use the new Fuel card instead of the Missing Link if HJ is enabled.

2. Use the Maniac instead of Deep Ones.

Thanks
Nicola

**Comment by scrubbless** [comment]
> Use the new Fuel card instead of the Missing Link if HJ is enabled.

I actually tried to patch this recently, however its not quite as easy to do. Without Variable text to say "fuel" or "Missing Link" I would have to duplicate all the events that involve the item with the alternate text. I can't think of an elegant solution for it as of yet.


> Use the Maniac instead of Deep Ones.

At the time, I wanted a variety with the monsters - all humanoids (mostly zombies) was a bit boring for me, so I wanted to add some external beasties from the sea. But I can see why it would be better keeping the monster thematic:

Deepone Hybrids/Thralls - Advanced infection
Riot - Groups of regular infected
Zombies - those that been recently infected
Maniac - those succumbing to the infection and being driven mad.

I want to make another pass at Stress and Strain to add some HJ content (maybe committing the time to un-pick that fuel issue) and to update the puzzle to a more interactive - graphical one like my latest scenarios. If its not too much issue I could probably replace those Deep-ones with Maniacs.

**Comment by NicolaZee** [comment]
**QItems**
For QItemQItemFuelCan

Firstly I'd rename it QItemFuelCan for Missing Link.
Then I'd add QItemFuelCanHJ for HJ Fuel Can

**Events**
Add two new events 
EventHoldingCellOpenMetalCab_Tile21FuelCan
EventHoldingCellOpenMetalCab_Tile21FuelCanHJ

Convert EventHoldingCellOpenMetalCab_Tile21 to call up these two events and add display=false

**Tokens**
Add two new events called from TokenBoatEscape_Tile1 
TokenBoatEscape_Tile1FuelCan (with check if not HJ)
TokenBoatEscape_Tile1FuelCanHJ (with check if HJ)


**Localization**
EventHoldingCellOpenMetalCab_Tile21 rename to EventHoldingCellOpenMetalCab_Tile21FuelCan
Duplicate entry for  EventHoldingCellOpenMetalCab_Tile21FuelCanHJ

TokenBoatEscape_Tile1 rename to TokenBoatEscape_Tile1FuelCan
Duplicate entry for TokenBoatEscape_Tile1FuelCanHJ

Simples!

If you want I can do this myself and email you the results but I'm confident you can do this yourself!
: )

**Comment by scrubbless** [comment]
Yeh I'll be able to do it, just not had time (or motivation) to sit down and do it!

Thanks for the info!

**Comment by scrubbless** [comment]
I've swapped out the Deep One out for the Maniac, in the campaign version of the scenario, I much prefer it so thank you. I'm going to pull this over to the official release.

I've already patched the official scenario with the HJ Fuel if the expansion is present.
