### ISSUE TITLE
[Stress and Strain v3.6] - Missing Link Evidence used when Horrific Journeys present

### ISSUE THREAD

**Issue by wolanskip** [scrubbless/PublishedScenarios#23]
**Improvement Requested**
The scenario gave the Missing Link evidence item despite Horrific Journeys expansion being available. Horrific Journeys provides a Fuel Unique Item card - this card could have been used to represent the Fuel needed in the level.

**Suggestion**
Add expansion detection and give the players the Fuel card if it is present in their collection instead of the Missing Link. Update text appropriately in that scenario.

**Comment by scrubbless** [comment]
Hi @wolanskip 

Sorry I took so long to respond to this. I've not been checking my repo issues!

That is a great idea, thanks for bringing it up. I have made this change in the campaign (which includes A Stress and Strain). I am not sure if I've reproduced those changes to the live scenario, but I will.

Thanks again
