### ISSUE TITLE
Item in space indicated

### ISSUE THREAD

**Issue by zaki850** [scrubbless/PublishedScenarios#3]
![image](https://user-images.githubusercontent.com/26735015/35351056-0b8f4112-0140-11e8-91c8-557021a4ad58.png)

"Place the lead pipe in the space indicated" - there is no space indicated (I understand it's the one where Thrall is, but still...)

**Comment by scrubbless** [comment]
This is just how the editor looks different to the actual game.
In the editor it shows a highlight symbol, but in game it shows the monster Icon.
![image](https://user-images.githubusercontent.com/32058089/35382943-ab1b9668-01b8-11e8-8513-64ea3db7ab67.png)

I'll have a think about how best to do this. Maybe i'll place the lead pipe in an event, then spawn the monster separately.

**Comment by scrubbless** [comment]
Out of curiosity, in your play through. Did you go right for the thrall or try to sneak around it?

**Comment by zaki850** [comment]
I sneaked (knocking on the door) and then stood where the search icon is. Next round I interacted by throwing the lead pipe I found (ranged attack).  :)

**Comment by scrubbless** [comment]
Adding an event is a pain in the backside, but I have realised that I didn't tell the player to remove the interact token anyway.

So I have come up with this:
![image](https://user-images.githubusercontent.com/32058089/35383132-4e49a276-01b9-11e8-8c48-b93b5bed5d9e.png)

**Comment by scrubbless** [comment]
> I sneaked (knocking on the door) and then stood where the search icon is. Next round I interacted by throwing the lead pipe I found (ranged attack). :)

A friend of mine said.. "Why am I throwing a metal spike at a monster when I have a tommy gun?"

He has a fair point, but I just thought it sounded cool, haha.

**Comment by zaki850** [comment]
Yeah, thought the same thing - was standing there with a rifle and was
throwing a pipe at a monster. ;)
