### ISSUE TITLE
Spanish translation - A strain on reality

### ISSUE THREAD

**Issue by vidimus** [scrubbless/PublishedScenarios#30]
Here is the file with the translation:
[Localization.Spanish.txt](https://github.com/scrubbless/PublishedScenarios/files/7834177/Localization.Spanish.txt)

Also it's here:
https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/Una%20deformaci%C3%B3n%20de%20la%20realidad

**Comment by vidimus** [comment]
Text for the images (Spanish version):

[Ingame text on pictures - Spanish version.xlsx](https://github.com/scrubbless/PublishedScenarios/files/7834162/Ingame.text.on.pictures.-.Spanish.version.xlsx)

**Comment by vidimus** [comment]
Audio files are pending. I will post them here in a few days

**Comment by vidimus** [comment]
Audios:

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/Una%20deformaci%C3%B3n%20de%20la%20realidad/Narracion_una_deformacion_de_la_realidad

**Comment by vidimus** [comment]
Hello, @scrubbless 
All the needed files are ready (voiceover, ingame text and translation).

**Comment by scrubbless** [comment]
Thanks @vidimus 

I'll try to start on this today 👍

**Comment by scrubbless** [comment]
Who would you like me to credit for the text translation and the audio?

The voice actor is amazing btw, no idea what shes saying but its very professional !

EDIT:

I also have to apologise, some of the end dialogues I wrote but didn't end up using. It got a bit complicated to place out the dialogues for nuanced endings (like ammi being saved, or killed). So there are about 5 readings there that are not used in the scenario.

**Comment by scrubbless** [comment]
Ok just a heads up on my progress:

I have integrated all of the audios, this meant also changing some of the exit music to your files (and then creating just filler music files for English and the other languages).

I have also imported the Spanish text file and linked it, looks good to me on a quick test.

I now have the long and arduous task of generating the image translations :grin: i'll get to that on my next parse of the scenario

**Comment by vidimus** [comment]
Great news. Credits for the voiceover:

Ingrid Carreras and Edko (¿A Qué Se Juega?)

**Comment by scrubbless** [comment]
Thanks @vidimus 


There seems to be a missing translation, do you have this on hand?

![image](https://user-images.githubusercontent.com/32058089/149509252-82b1af1c-2a5f-4e80-8740-3861ca947c18.png)

The english is this one:
![pageburnt](https://user-images.githubusercontent.com/32058089/149509409-7b833c67-cc73-4016-9781-d8ac1bf78290.png)

**Comment by scrubbless** [comment]
No need to translate the "project clarify" image, I have that translation (as the image is used 3 times and you've translated one of the others)

I just need the bits of smudged black text

**Comment by scrubbless** [comment]
I've been using your repo as a workspace for the translations, I hope thats ok. I've added the .XCF files and started to export the files out, once complete i'll copy all this information to the scenario (and my repos for dev) and publish the new scenario.

I just thought you might be interested in the background stuff that goes into the images I use.

**Comment by vidimus** [comment]
> Thanks @vidimus
> 
> There seems to be a missing translation, do you have this on hand?
> 
> ![image](https://user-images.githubusercontent.com/32058089/149509252-82b1af1c-2a5f-4e80-8740-3861ca947c18.png)
> 
> The english is this one: ![pageburnt](https://user-images.githubusercontent.com/32058089/149509409-7b833c67-cc73-4016-9781-d8ac1bf78290.png)

Here's the translation:

**Left column:**

He conseguido rescatar algunos papeles que había en la chimenea de la oficina de la doctora Little.

Este borrador desechado de una carta quizá pueda probar los planes de la Dra. Little.

No sólo deja claro que ha estado experimentando con sus pacientes sino que además menciona a una misteriosa tercera parte implicada que estaría financiando el proyecto.

**Right column:**

Es una pena no poder sacar más información de los documentos del fuego.

**Comment by vidimus** [comment]
> I've been using your repo as a workspace for the translations, I hope thats ok. I've added the .XCF files and started to export the files out, once complete i'll copy all this information to the scenario (and my repos for dev) and publish the new scenario.
> 
> I just thought you might be interested in the background stuff that goes into the images I use.

No problem. I have seen some mistakes, like an image with Polish text instead of Spanish.

Edit: OK, it was the pageburnt picture. This is why I didn't translated it.

**Comment by vidimus** [comment]
In this one, "Rowley Asylum" is not translated. It should be "Manicomio de Rowley".

![image](https://user-images.githubusercontent.com/41538948/149634591-8b15edcb-5298-41ce-9ae2-3f1bdb9b821f.png)

**Comment by scrubbless** [comment]
![secrettip](https://user-images.githubusercontent.com/32058089/149809919-d46e40ec-bc7e-4c8a-a05d-501ffa30e711.png)

Here is the secrettip.png that was not translated.

**Comment by scrubbless** [comment]
Here is the burnt page, no need to do the page i've updated that bit.
![image](https://user-images.githubusercontent.com/32058089/149810530-db90dc21-c3aa-41b5-a4c0-2e4f32e40be3.png)

**Comment by scrubbless** [comment]
> In this one, "Rowley Asylum" is not translated. It should be "Manicomio de Rowley".
> 
> ![image](https://user-images.githubusercontent.com/41538948/149634591-8b15edcb-5298-41ce-9ae2-3f1bdb9b821f.png)

Done

**Comment by scrubbless** [comment]
> > Thanks @vidimus
> > There seems to be a missing translation, do you have this on hand?
> > ![image](https://user-images.githubusercontent.com/32058089/149509252-82b1af1c-2a5f-4e80-8740-3861ca947c18.png)
> > The english is this one: ![pageburnt](https://user-images.githubusercontent.com/32058089/149509409-7b833c67-cc73-4016-9781-d8ac1bf78290.png)
> 
> Here's the translation:
> 
> **Left column:**
> 
> He conseguido rescatar algunos papeles que había en la chimenea de la oficina de la doctora Little.
> 
> Este borrador desechado de una carta quizá pueda probar los planes de la Dra. Little.
> 
> No sólo deja claro que ha estado experimentando con sus pacientes sino que además menciona a una misteriosa tercera parte implicada que estaría financiando el proyecto.
> 
> **Right column:**
> 
> Es una pena no poder sacar más información de los documentos del fuego.

Done

**Comment by vidimus** [comment]
> ![secrettip](https://user-images.githubusercontent.com/32058089/149809919-d46e40ec-bc7e-4c8a-a05d-501ffa30e711.png)
> 
> Here is the secrettip.png that was not translated.


Información.

Haz clic sobre la pantalla en el lugar en el que pienses que está el interruptor oculto.

Se te pedirá que confirmes tu elección.

Si fallas, el rompecabezas se cerrará y tendrás que usar una nueva acción para volver a intentarlo.

Haz clic para salir...
