### ISSUE TITLE
Torches Issue

### ISSUE THREAD

**Issue by zaki850** [scrubbless/PublishedScenarios#8]
Do not remember everything, but I think after lighting up the torches next to the bookshop, the action (search token) is still there for some reason even though they are already lit and there is no more darkness. Not sure if that was for purpose and lighting them again would trigger something else but it's worth checking.

**Comment by scrubbless** [comment]
I noticed this one during the version 2 re-write. I had forgotten to remove the component once completing the test.

There is now more incentive to light the torches now and the search token will not remove after taking a torch. Giving the player an option to take a torch, then light the rest.

Pass or fail the torches will be lit and the token is removed now. I assume you didn't fail the test when you did it? ;)

![image](https://user-images.githubusercontent.com/32058089/35381730-1f455302-01b5-11e8-9c2e-9501d56d9cff.png)

**Comment by zaki850** [comment]
Actually, I did - fell down and started a fire, but still the torches were lit. :)

**Comment by scrubbless** [comment]
Yeh, the idea being you managed to light them before falling :D
Its such a minor perk and it made thematic sense.

I did notice that the fire was not removed after being placed, so I have corrected that too. The app can't track fire, so the tokens need to be removed.
